### 数据操作
##### 创建NDarray

`nd.arange()` 

`x.shape `返回形状

`x.size `返回元素个数

`x.reshape(m, n)`
- -1的省去维度的计算

`nd.zeros(shape = (w, h, d))`

`nd.ones(shape = ())`

`nd.random.normal(均值，方差， shape = ())`

In [1]:
from mxnet import nd

In [3]:
x = nd.arange(12)
x


[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

In [4]:
x.shape

(12,)

In [5]:
x.size

12

In [8]:
X = x.reshape(3,4)
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

- x.reshape() 中-1的元素的个数可以由总的个数和其他维度的大小推断出

In [11]:
x.reshape(-1, 3)


[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]
<NDArray 4x3 @cpu(0)>

In [12]:
x.reshape(2, -1)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]]
<NDArray 2x6 @cpu(0)>

In [15]:
nd.zeros((2, 3, 4))
# zeros(shape, ctx, dtype, stype, **kwargs)


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [17]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [21]:
Y = nd.array([[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]])
Y


[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<NDArray 3x3 @cpu(0)>

In [25]:
nd.random.normal(0, 1, shape = (3, 4))
# normal(loc, scale, shape, dtype, ctx, out, **kwargs)


[[-0.68106437 -0.13531584  0.37723127  0.41016445]
 [ 0.5712682  -2.7579627   1.07628    -0.6141326 ]
 [ 1.8307649  -1.1468065   0.05383795 -2.5074806 ]]
<NDArray 3x4 @cpu(0)>

##### NDarray 运算
支持运算符+，- ，\*， /

其中\*，/为对应位元素相乘（除）

In [31]:
X = x.reshape(3,4)
X


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [32]:
Y = nd.ones((3,4)) * 2
Y


[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
<NDArray 3x4 @cpu(0)>

In [33]:
X / Y


[[0.  0.5 1.  1.5]
 [2.  2.5 3.  3.5]
 [4.  4.5 5.  5.5]]
<NDArray 3x4 @cpu(0)>

In [34]:
# e的指数运算
X.exp()


[[1.0000000e+00 2.7182817e+00 7.3890562e+00 2.0085537e+01]
 [5.4598148e+01 1.4841316e+02 4.0342880e+02 1.0966332e+03]
 [2.9809580e+03 8.1030840e+03 2.2026465e+04 5.9874141e+04]]
<NDArray 3x4 @cpu(0)>

In [46]:
# 矩阵乘法
X.shape, Y.shape

((3, 4), (3, 4))

In [45]:
nd.dot(X, Y.T)


[[12. 12. 12.]
 [44. 44. 44.]
 [76. 76. 76.]]
<NDArray 3x3 @cpu(0)>

In [50]:
nd.concat(X, Y)
# 相当于dim = 最后一个维度，即在该维度上进行拼接扩展；此处dim = 1，列上进行增加


[[ 0.  1.  2.  3.  2.  2.  2.  2.]
 [ 4.  5.  6.  7.  2.  2.  2.  2.]
 [ 8.  9. 10. 11.  2.  2.  2.  2.]]
<NDArray 3x8 @cpu(0)>

In [53]:
nd.concat(X,Y, dim = 0)


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
<NDArray 6x4 @cpu(0)>

In [57]:
# 条件判断式
# 判断对应位置元素是否相同
X.T, nd.arange(12).reshape(4, -1)

(
 [[ 0.  4.  8.]
  [ 1.  5.  9.]
  [ 2.  6. 10.]
  [ 3.  7. 11.]]
 <NDArray 4x3 @cpu(0)>, 
 [[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]
  [ 9. 10. 11.]]
 <NDArray 4x3 @cpu(0)>)

In [58]:
X.T ==  nd.arange(12).reshape(4, -1)


[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 1.]]
<NDArray 4x3 @cpu(0)>

In [60]:
X.sum()
# 返回一个1x1的NDarray


[66.]
<NDArray 1 @cpu(0)>

In [64]:
X.norm()


[22.494442]
<NDArray 1 @cpu(0)>

- 上述X.exp()、X.sum()、X.norm()可以改写成nd.exp(X)、nd.sum(X)、nd.norm(X)
- 1x1NAarray可以用asscalar()函数转化为python中的标量

##### 广播机制
- 只有形状不同的数组都可以复制成相同形状的条件下，才能触发广播机制

In [67]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1, 2))
A, B

(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

In [68]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

###### 索引
- 遵循左闭右开的原则
- 索引从0开始
- 索引截取范围采用‘:’，例：【1：3】表示索引为1,2的两部分

In [73]:
print(X)
X[2,2]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>



[10.]
<NDArray 1 @cpu(0)>

In [74]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

#### 自动求梯度
1. 申请存储梯度内存x.attach_grad()
2. 调用autograd.record()记录求解梯度相关计算
3. 调用y.backward()计算函数y对x的导数
   - 当y结果不是标量时，会默认对y中的元素求和后，再计算相关梯度

In [75]:
from mxnet import nd, autograd

In [84]:
x = nd.arange(4).reshape((4,1))
x


[[0.]
 [1.]
 [2.]
 [3.]]
<NDArray 4x1 @cpu(0)>

In [85]:
x.attach_grad()
# 申请存储梯度所需的内存

In [86]:
with autograd.record():
# 调用record时才会记录求梯度的有关计算
    y = 2 * nd.dot(x.T, x) #y的形状是一个标量

In [87]:
y.backward()
# 调用backward对之前申请的x自动求导，即2x平方的对x求导数

In [88]:
x.grad


[[ 0.]
 [ 4.]
 [ 8.]
 [12.]]
<NDArray 4x1 @cpu(0)>

In [92]:
x.attach_grad()
# 申请存储梯度所需的内存
with autograd.record():
# 调用record时才会记录求梯度的有关计算
    y = 2 * nd.dot(x, x.T) 
    print(y.shape)
y.backward()
y, x.grad

(4, 4)


(
 [[ 0.  0.  0.  0.]
  [ 0.  2.  4.  6.]
  [ 0.  4.  8. 12.]
  [ 0.  6. 12. 18.]]
 <NDArray 4x4 @cpu(0)>, 
 [[24.]
  [24.]
  [24.]
  [24.]]
 <NDArray 4x1 @cpu(0)>)